---
# App specific
dp3t:
  ibcovid:
    auth:
      # JWT expiration in minutes
      jwt-time-to-live: 60

# Server settings
server:
  port: 10103

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  # Database
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: "sa"
    password: ""

# Logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.SQL.type.descriptor.sql: TRACE
    es.caib.dp3t.ibcovid: DEBUG
