---
# App specific
dp3t:
  ibcovid:
    auth:
      # JWT expiration in minutes
      jwt-time-to-live: 60

# Server settings
server:
  port: 10103

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/dpppt
    driver-class-name: org.postgresql.ds.PGSimpleDataSource
    username: "postgres"
    password: "root"

# Logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.SQL.type.descriptor.sql: TRACE
    es.caib.dp3t.ibcovid: DEBUG
